name: macstadium-build-sdk-android

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  ANDROID_HOME: /Users/administrator/Library/Android/sdk

jobs:
  build:
    name: build-sdk-android
    runs-on: self-hosted
    outputs:
      artifact-url: ${{ steps.upload-artifact.outputs.artifact-url  }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build APK with Gradle
        run: ./gradlew clean --refresh-dependencies assembleDebug
      - name: Check folder with APK
        run: ls -la ./cloudx-demo/build/outputs/apk/debug
      - name: upload-artifact
        id: upload-artifact
        uses: actions/upload-artifact@master
        with:
          name: cloudx-sdk-android-apk
          path: ./cloudx-demo/build/outputs/apk/debug/cloudx-demo-debug-0.0.0.apk

  dispatch:
    name: trigger-autotest
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'cloudx-xenoss',
              repo: 'cloudexchange.sdk.android.automated.testing',
              workflow_id: 'android.yml',
              ref: 'master',
              inputs: {
                'artifact-url' : '${{ needs.build.outputs.artifact-url }}',
              },
            });